<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'B13\\Container\\' => array($typo3InstallDir . 'typo3conf/ext/container/Classes'),
    'GridElementsTeam\\Gridelements\\' => array($typo3InstallDir . 'typo3conf/ext/gridelements/Classes'),
    'IchHabRecht\\ContentDefender\\' => array($typo3InstallDir . 'typo3conf/ext/content_defender/Classes'),
    'Jramke\\TailwindStyledContent\\' => array($typo3InstallDir . 'typo3conf/ext/tailwind_styled_content/Classes'),
    'T3SBS\\T3sbootstrap\\' => array($typo3InstallDir . 'typo3conf/ext/t3sbootstrap/Classes'),
    'Vendor\\SitePackage\\' => array($typo3InstallDir . 'typo3conf/ext/site_package/Classes'),
);
